[build]
command = "gatsby build"
publish = "public"


[build.environment]
 NODE_VERSION = "18.17.1"
 NPM_VERSION = "9.6.7"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  output_path = "reports/lighthouse.html"
[[plugins]]
  package = "@netlify/plugin-gatsby"    
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=2592000'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = '''
      https://dev2.viadelweb.com,
       
    '''      
    Access-Control-Allow-Methods = '''
      POST, 
      GET,
      PUT,  
      DELETE,
      HEAD
    '''
    Access-Control-Allow-Credentials = "true"
    Vary = "Accept-Encoding"
    Permissions-Policy = '''
      accelerometer=(self),
      ambient-light-sensor=(self),
      autoplay=(self),
      camera=(self),
      encrypted-media=(self),
      fullscreen=(self),
      geolocation=(self),
      gyroscope=(self),
      magnetometer=(self),
      microphone=(self),
      midi=(self),
      payment=(self),
      picture-in-picture=(self),
      usb=(self),
      vr=(self)
    '''
    Content-Security-Policy-Report-Only = '''
      default-src 'self'; 
      script-src 'self' 'unsafe-inline' https://*.viadelweb.com https://api.netlify.com https://netlify.com https://link.msgsndr.com; 
      style-src 'self' 'unsafe-inline' https://api.leadconnectorhq.com https://*.leadconnectorhq.co; 
      img-src 'self' data: https://images.unsplash.com; 
      font-src 'self' data: https://*.viadelweb.com; 
      connect-src 'self' https://*.viadelweb.com https://identity.netlify.com https://netlify.com https://*.netlify.com https://api.github.com https://ocsp.digicert.com; 
      media-src 'self'; 
      object-src 'self'; 
      child-src 'self' https://api.leadconnectorhq.com; 
      frame-src 'self' https://api.leadconnectorhq.com; 
      worker-src 'self'; 
      form-action 'self' https://netlify.com https://*.netlify.com;
      upgrade-insecure-requests; 
      block-all-mixed-content; 
      manifest-src 'self'
      '''
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=31536000'''
