[build]
command = "gatsby build"
publish = "public"


[build.environment]
 NODE_VERSION = "18.17.1"
 NPM_VERSION = "9.6.7"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  output_path = "reports/lighthouse.html"
[[plugins]]
  package = "@netlify/plugin-gatsby"    
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=2592000'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = '''
      https://dev2.viadelweb.com,
      https://m.rblartdesign.com,
      https://m.rblartdesign.com/stats.js,
      https://github.com, 
      https://identity.netlify.com, 
      https://media-library.cloudinary.com, 
      https://widget.cloudinary.com, 
      https://www.youtube.com,
    '''      
    Access-Control-Allow-Methods = '''
      POST, 
      GET,
      PUT,  
      DELETE,
      HEAD
    '''
    Access-Control-Allow-Credentials = "true"
    Vary = "Accept-Encoding"
    Permissions-Policy = '''
      accelerometer=(self),
      ambient-light-sensor=(self),
      autoplay=(self),
      camera=(self),
      encrypted-media=(self),
      fullscreen=(self),
      geolocation=(self),
      gyroscope=(self),
      magnetometer=(self),
      microphone=(self),
      midi=(self),
      payment=(self),
      picture-in-picture=(self),
      speaker=(self),
      usb=(self),
      vibrate=(self),
      vr=(self)
    '''
    Content-Security-Policy = "connect-src 'self' blob:  https://m.rblartdesign.com/stats.js https://github.com https://identity.netlify.com https://www.youtube.com https://res.cloudinary.com https://api.github.com https://ocsp.digicert.com; form-action 'self'; font-src 'self' blob: data: https://m.rblartdesign.com; frame-src 'self' https://m.rblartdesign.com  https://www.youtube.com  https://api.leadconnectorhq.com; img-src 'self' blob: data: https://api.netlify.com https://images.unsplash.com; manifest-src 'self'; media-src 'self' blob: https://m.rblartdesign.com https://images.unsplash.com; object-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://m.rblartdesign.com https://api.netlify.com https://netlify.com https://res.cloudinary.com https://www.youtube.com; script-src-elem 'self' blob: 'unsafe-inline' https://m.rblartdesign.com/stats.js https://www.youtube.com https://link.msgsndr.com/js/form_embed.js; style-src 'self' 'unsafe-inline' https://m.rblartdesign.com https://github.com https://identity.netlify.com https://res.cloudinary.com  https://www.youtube.com https://m.rblartdesign.com/stats.js; prefetch-src 'self' blob: https://link.msgsndr.com/js/form_embed.js https://api.leadconnectorhq.com;  worker-src 'self' blob: https://m.rblartdesign.com;"
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=31536000'''
